apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet
  labels:
    app: intranet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intranet
  template:
    metadata:
      labels:
        app: intranet
    spec:
      containers:
        - name: intranet-container
          image: nexus.jdevhub.com/intranet:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: intranet
spec:
  selector:
    app: intranet
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # port expos√© dans le cluster
      targetPort: 80    # port dans le container
      nodePort: 30080
  
