apiVersion: apps/v1
kind: Deployment
metadata:
  name: tornado
  labels:
    app: tornado
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tornado
  template:
    metadata:
      labels:
        app: tornado
    spec:
      containers:
        - name: tornado-container
          image: nexus.jdevhub.com/tornado:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: tornado
spec:
  selector:
    app: tornado
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # port expos√© dans le cluster
      targetPort: 80    # port dans le container
      nodePort: 30080
  
